/** code generated by Kinyoshi */
package net.minecraft.src;

public class mod_CraftGunpowder extends BaseMod
{
	public void load()
	{

        ModLoader.addShapelessRecipe(new ItemStack(Item.gunpowder, 4), new Object[] {Item.coal, Item.flint, Item.sugar, new ItemStack(Item.dyePowder, 1, 15)});
        ModLoader.addShapelessRecipe(new ItemStack(Item.gunpowder, 4), new Object[] {new ItemStack(Item.coal, 1, 1), Item.flint, Item.sugar, new ItemStack(Item.dyePowder, 1, 15)});
 
    }

	public String getVersion() {
		return "1.5.1";
	}

}
